str1=str(input("enter your name:-"))
f=open("output.txt","w")
f.write(str1)
f.close()
f=open("output.txt","a")
f.write(" learning file handling in python")
f.close()
f=open("output.txt","r")
print(f.read())
f.close()